

// export const metadata: Metadata = {
//     title: "Design Role | Home",
//     description: "Generated by create design role",
// };

import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navbar";

export default  function HomeLayout({ children }: Readonly<{ children: React.ReactNode }>) {


    return (
        <div>
            <div>
                <Navbar />
            </div>
            <div className="min-h-screen mx-auto ">
                {children}
            </div>
            <Footer />
        </div>
    );
}